#pragma once

#define DEF_MSCN_RAND_C_MIN 2
#define DEF_MSCN_RAND_C_MAX 20
#define DEF_MSCN_RAND_S_MIN 1
#define DEF_MSCN_RAND_S_MAX 1000
#define DEF_MSCN_RAND_U_MIN 1
#define DEF_MSCN_RAND_U_MAX 3
#define DEF_MSCN_RAND_P_MIN 60
#define DEF_MSCN_RAND_P_MAX 500


#define NUMBER_OF_SUPPLIERS 2
#define NUMBER_OF_FACTORIES 1
#define NUMBER_OF_DESTRIBUTION_CENTERS 3
#define NUMBER_OF_SHOPS 4

#define DEFAULT_TABLE_LENGTH 5
#define DEFAULT_TABLE_NAME "DefaultTable"